include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: error
  exclude:
    - build/**
    - android/**

linter:
  rules:
    avoid_print: true
    prefer_final_locals: true
    always_declare_return_types: true
    unawaited_futures: true
    avoid_empty_else: true
    unnecessary_lambdas: true
    use_super_parameters: true
