// Generated by FlutterFire CLI — do not edit by hand.
//
// Source: android/app/google-services.json for the `victoria-fabrics` project.
// Re-generate with `flutterfire configure` whenever a platform is added.
//
// This file must not be committed if the project ever moves to a public repo
// with a restricted API key; today the key is already shipped inside
// google-services.json, so there is no additional exposure.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBSZ-7bMCLN2kGVI7JoTU0W27wHnn3Uzk',
    appId: '1:1010144166475:android:27384e1b5bc8721b02c3ce',
    messagingSenderId: '1010144166475',
    projectId: 'victoria-fabrics',
    storageBucket: 'victoria-fabrics.firebasestorage.app',
  );
}